### PR TITLE
Standard

### PR DESCRIPTION
**Pull request by heavyk**
hey dude. I added two missing error listeners (pushed that code to the other PR too).

however two things were bothered me, and those were the semicolons and the `fromFile` api. so I converted the code to standard and made `fromFile` api consistent (no functionality is lost; see the example). feel free to take what you want. I didn't add more tests, but I can say that it is definitely working in "production" ... just thought to contribute back

cheers

### CODE REVIEW

**Comment by LewisJEllis** [comment]
The fromFile API does feel kind of strange, and I'd like something that feels more normal, but there is actually a small use case hurt by the change. If I want to get the ID and do something with it before I actually go and save the file to GridFS, I can't do that with this change. I'll give this some thought and see if I can come up with either a better way for this to work without compromising that use case; let me know if you have any ideas.

As for Standard - while I like its mission, and I would rather someone use Standard than use nothing, I have some reasons not to adopt it. I would be able to live without semicolons, and I have before, but I find that matter fairly unimportant; what I don't like, though, is the "space after function name" thing. If we include a space after the function name, then perhaps we ought to write all our anonymous function expressions as `function <delete> (arg...)` with two spaces, since the name is just the empty string! Instead, without that space, `function (arg...)` and `function name(arg...)` are consistent with each other. This is one spot where I think "Standard" is not so standard; the Airbnb, jQuery, Google, Idiomatic.js, and Node.js style guides all disagree with it.

Furthermore, just using ESLint (which Standard uses anyway, and which I'm [decently familiar with](https://github.com/LewisJEllis/eslint101)) lets us enforce more good rules that Standard chooses not to, like `no-use-before-define` and `camelcase` and `space-in-brackets`.

**Comment by heavyk** [comment]
yeah, so I didn't check if this works, but because it returns the stream, you _should_ be able to `.pause()` it for as long as you want.

but, I think I see what you're trying to say though: for example in our foto upload part, I just call `ObjectID()` to generate one and then I can use that id to save a reference into the user's fotos. at any time I want, I can call `fromFile` and just pass {_id: id} into the options. it's passed on the gridfs-stream.createWriteStream which just calls `ObjectID()` if `_id == null`

to each his own on style preference :) I used to be a tab guy myself (4 virtual spaces). node's "callback hell" helped me to convert to 2 virtual spaces, and then maybe now that I'm older (or something), I just completely stopped caring. it seemed obvious to me that forcing two spaces is just to ensure no one would ever see node programs on 4 or omg how horrible it would be, 8 virtual spaces... lol

so, I promised myself, my next big project would be my own editor which treated all spaces to the right of newlines special two spaces chars. they would behave nearly identical to how tabs worked. actually, I could make them work however I wanted. this gave me a lot of good ideas: I could even make all js functions look like an arrow, regardless of the ES version I'm wrting in.

**Comment by LewisJEllis** [comment]
Hm, I commented here earlier but I'm not sure where it went. Anyway, I like the idea of leaving it to the user's application logic to worry about passing around ObjectIds if necessary. It seems the API design was tainted by how my application was handling the ObjectId back when I was just using gridfs-stream before creating this wrapper. @heavyk I made the changes in https://github.com/LewisJEllis/gridfs/commit/805fa5077405897e4816eb852f15a899c0226cb5 but I guess you already saw that. I also made the change for returning `ws`, but I'm still unsure about how you seemed to want to return `rs` in toFile; I don't see any need or use. Let me know about that and then I'll publish version 1.0.0 to npm.

**Comment by heavyk** [comment]
lol, I didn't see/have any use either... honestly, it was one of those, "ah, what the the hell, it's got to return _something_" moments :) the important one was the the `ws` cause that's the one I use...

cheers mate. I'll put this code up later today. so far, seems to be working fine.

**Pull request closed without merging**
